name: Docker Image CI

on:
  push:
    branches: ["stage"]
    # tags:
    #   - '*'

env:
  REGISTRY: cachac
  IMAGE_NAME: kubelabs_publicapi_test

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/stage'

    steps:
      - uses: actions/checkout@v3 # checkout github code
        name: Checkout code

      - name: Get TAG version
        run: echo "RELEASE_VERSION=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV

      - name: Echo New Tag Version
        run:  echo ${{ env.RELEASE_VERSION }}

      - name: Get current branch
        run: |
          echo "TAG=$(git tag | sort -V | tail -1)"
          echo "Branch is ${{env.TAG}}."
          echo "::set-output name=TAG::${{env.TAG}}"
          echo "OUTPUT Branch is ${{env.TAG}}."


# git rev-parse --short HEAD

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build & Push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     # file: ./path-to-dockerfile
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB_REF_NAME }}
      #     build-args: |
      #       APP_ENV=${{ secrets.APP_ENV }}





    # DOCKER RUN to test container
    # - name: Build the Docker image
    #   run: docker run --rm --name api -p 3000:3000 cachac/kubelabs_publicapi_test






# EXTRA
# - uses: "marvinpinto/action-automatic-releases@latest"
    #   name: Release
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: ${{ env.VERSION }}
    #     title: ${{ env.RELEASE }}
    #     prerelease: false
