name: Docker Image CI

on:
  push:
    branches: [ "stage" ]

env:
  REGISTRY: cachac
  IMAGE_NAME: kubelabs_publicapitemp

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # checkout github code
      name: Checkout code


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push
      uses: docker/build-push-action@v3
      with:
        push: true
        # file: ./path-to-dockerfile
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          APP_ENV="${{ secret.APP_ENV }}"

    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   name: Release
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: ${{ env.VERSION }}
    #     title: ${{ env.RELEASE }}
    #     prerelease: false

    # - name: Build the Docker image
    #   run: docker build . --tag "${{ env.REGISTRY }}:${{ env.IMAGE_NAME }}"  --build-arg APP_ENV="${{ secret.APP_ENV }}"

